### ISSUE TITLE
Create a sandstorm package

### ISSUE THREAD

**Issue by neynah** [iwazaru/polytunes#2]
Hi!

I'm the designer at [sandstorm.io](http://sandstorm.io) and I came across your app and thought it was really awesome (and cool looking). We're currently looking for unique open-source apps to add to our [App Market](https://apps.sandstorm.io/).

Would your team possibly be interested in helping me get your app running on Sandstorm so that others can quickly install & create instances of Polytunes? I attempted to package it myself but ran into issues with trying to have another user join- you can try the demo to see for yourself [here](https://oasis.sandstorm.io/appdemo/380xsyjmchzzgxy5n6m0gen8cy7rtr9raqkhcckx27vvvhcg9zwh).

I'm pretty excited about this so if you decide you are interested in helping me get this to a workable state, I'd be more than willing to help with any graphics/logos(if you'd like).

Cheers! :)

**Comment by clemlatz** [comment]
Hey neynah, thanks for you interest in Polytunes. 

To invite another user to play with you, you need to share the page url containing the room id (e.g. /room/xxxx). Looks like you're running Polytunes in a iframe so even if you "share access", the other user will be redirected to the app's homepage rather than your room. Is there a way in Sandstorm to share an url to a specific page with the access ?

**Comment by paulproteus** [comment]
Hi @iwazaru,

I'm one of the core devs of Sandstorm, collaborating with @neynah.

And yes, it's definitely possible to change how `Share access` works so that the other user will join the room that was just created. The way I would probably code it is:
- If you're the first user in the app instance, then you see the same UI that @neynah already has working, and
- If you're another user after them, then you join whatever room was created.

To create multiple rooms, I would suggest using the "New instance" feature of Sandstorm and create a second instance of the app.

Maybe I can work with @neynah on some code changes in the Sandstorm package, and give you an updated demo link. Alternatively if you find this interesting, I can show you how to use our packaging tools and make similar changes.

I'm probably not going to have time to work on this until Monday Nov 2, so no massive rush; let me know what you think!

**Comment by clemlatz** [comment]
Hi @paulproteus, thanks again for your interest in Polytunes. Sandstorm sure looks great. 

I don't have a lot of time to work of Polytunes which is a side project for me, and I'd rather concentrate on the core development than on specific plateforms implementations. So go ahead and work on the Sandstorm package and let me know if you have any questions (you can [contact me directly here](http://nokto.net/contact/)). If the Sandstorm implementation requires changes in the Polytunes code (maybe a "single room mode" would help ?), please open a new github issue and I'll see what I can do.

Anyway, because Polytunes is very young and I'm using to learn Meteor, there a good changes I'll make a lot of breaking changes in future versions. Maybe it would be wiser to wait for 1.0 to work on a Sandstorm package ? Anyway, that's up to you.

**Comment by paulproteus** [comment]
I think doing some packaging now is probably pretty reasonable, even if
some stuff might break. I'll put this on my queue! Thanks for the reply.

**Comment by mquandalle** [comment]
Hey, I’m the author of [Wekan](https://github.com/wekan/wekan), another Meteor application available on the Sandstorm App market. I’m a little bit busy right now so I can’t directly write a PR to support Polytunes on Sandstorm but I would be happy to help here if anyone has a question. I also encourage whoever plan to work on this integration to take a look at my [sandstorm.js](https://github.com/wekan/wekan/blob/devel/sandstorm.js) file that basically implement all the Sandstorm related logic.

(by the way Polytunes team, we were next to each other at the Meteor hackathon in Paris ;-) We were working on Brio — that I would also like to port on Sandstorm once I get some time)

**Comment by clemlatz** [comment]
Hi @mquandalle, I remember very well breaking your meteor-bower package during the hackathon and asking you about it ;) Just a few days ago I was trying to remember who at hackathon talked about an open-source alternative to Trello, I guess it was Wekan, so thanks for the link and for your sandstorm.js file!

**Comment by erikmaarten** [comment]
Hello everybody! @paulproteus nudged me into packaging this app for Sandstorm, so I'll give it go. Just to let you know somebody's working on it! :-)

**Comment by neynah** [comment]
@erikmaarten you're awesome! That's wonderful news.

@iwazaru I'll open a new issue for logo//graphics. :)

**Comment by neynah** [comment]
Hi! Just wondering if any progress has been made. Let me know if there's anything I can help with @erikmaarten & @iwazaru.

**Comment by erikmaarten** [comment]
@neynah My fork does work with Sandstorm to some extent, but not very well, and I haven't been working on it for a long time due to other priorities... I wouldn't count on myself to pick up work on this again in the near future :(
